// <auto-generated />
namespace BudgetSystem.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modifieddb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifieddb));
        
        string IMigrationMetadata.Id
        {
            get { return "202112130313414_modifieddb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
