// <auto-generated />
namespace BudgetSystem.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editBoxB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editBoxB));
        
        string IMigrationMetadata.Id
        {
            get { return "202108301628542_editBoxB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
