// <auto-generated />
namespace BudgetSystem.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EditedColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditedColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "202108131015079_EditedColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
